// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportsManagements;

#nullable disable

namespace ReportsManagements.Migrations
{
    [DbContext(typeof(ReportsDbContext))]
    [Migration("20251005062934_PendingChangesFix")]
    partial class PendingChangesFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reports")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportsManagements.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttId"));

                    b.Property<int?>("CapturedPhotoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FaceMatchScore")
                        .HasColumnType("float");

                    b.Property<int?>("GeolocationId")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("LivenessScore")
                        .HasColumnType("float");

                    b.Property<int?>("ReasonCodeId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttId");

                    b.HasIndex("CapturedPhotoId");

                    b.HasIndex("GeolocationId");

                    b.HasIndex("ReasonCodeId");

                    b.ToTable("AttendanceRecord", "reports");
                });

            modelBuilder.Entity("ReportsManagements.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches", "reports");
                });

            modelBuilder.Entity("ReportsManagements.Models.BranchReport", b =>
                {
                    b.Property<int>("BranchReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchReportId"));

                    b.Property<int>("AttendanceRate")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("TotalInstructors")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("BranchReportId");

                    b.ToTable("BranchReports", "reports");
                });

            modelBuilder.Entity("ReportsManagements.Models.CourseReport", b =>
                {
                    b.Property<int>("CourseReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseReportId"));

                    b.Property<decimal>("AverageAttendanceRate")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("CourseReportId");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("CourseReports", "reports");
                });

            modelBuilder.Entity("ReportsManagements.Models.FileStorage", b =>
                {
                    b.Property<int>("FileStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileStorageId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileStorageId");

                    b.ToTable("FileStorages", "reports");
                });

            modelBuilder.Entity("ReportsManagements.Models.Geolocation", b =>
                {
                    b.Property<int>("GeolocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeolocationId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RediusMeters")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GeolocationId");

                    b.ToTable("Geolocations", "reports");
                });

            modelBuilder.Entity("ReportsManagements.Models.ReasonCode", b =>
                {
                    b.Property<int>("ReasonCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonCodeId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReasonCodeId");

                    b.ToTable("ReasonCodes", "reports");

                    b.HasData(
                        new
                        {
                            ReasonCodeId = 1,
                            Category = "Attendance",
                            Code = "LATE",
                            IsActive = true,
                            Name = "Late"
                        },
                        new
                        {
                            ReasonCodeId = 2,
                            Category = "Health",
                            Code = "SICK",
                            IsActive = true,
                            Name = "Sick"
                        },
                        new
                        {
                            ReasonCodeId = 3,
                            Category = "System",
                            Code = "TECH",
                            IsActive = true,
                            Name = "Technical Issue"
                        });
                });

            modelBuilder.Entity("ReportsManagements.Models.TrainerReport", b =>
                {
                    b.Property<int>("TrainerReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerReportId"));

                    b.Property<decimal>("AttendanceRate")
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("TrainerReportId");

                    b.HasIndex("TrainerId", "CourseId")
                        .IsUnique();

                    b.ToTable("TrainerReports", "reports");
                });

            modelBuilder.Entity("ReportsManagements.Models.AttendanceRecord", b =>
                {
                    b.HasOne("ReportsManagements.Models.FileStorage", "CapturedPhoto")
                        .WithMany()
                        .HasForeignKey("CapturedPhotoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReportsManagements.Models.Geolocation", "Geolocation")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("GeolocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReportsManagements.Models.ReasonCode", "ReasonCode")
                        .WithMany()
                        .HasForeignKey("ReasonCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CapturedPhoto");

                    b.Navigation("Geolocation");

                    b.Navigation("ReasonCode");
                });

            modelBuilder.Entity("ReportsManagements.Models.Geolocation", b =>
                {
                    b.Navigation("AttendanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
