// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement;

#nullable disable

namespace UserManagement.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20251006061631_iupdatenitial")]
    partial class iupdatenitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BatchInstructor", b =>
                {
                    b.Property<int>("BatchesBatchId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorsInstructorId")
                        .HasColumnType("int");

                    b.HasKey("BatchesBatchId", "InstructorsInstructorId");

                    b.HasIndex("InstructorsInstructorId");

                    b.ToTable("BatchInstructor", "users");
                });

            modelBuilder.Entity("InstructorTrainee", b =>
                {
                    b.Property<int>("InstructorsInstructorId")
                        .HasColumnType("int");

                    b.Property<int>("TraineesTraineeId")
                        .HasColumnType("int");

                    b.HasKey("InstructorsInstructorId", "TraineesTraineeId");

                    b.HasIndex("TraineesTraineeId");

                    b.ToTable("InstructorTrainee", "users");
                });

            modelBuilder.Entity("UserManagement.Models.Admin_Profile", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.ToTable("AdminProfiles", "users");
                });

            modelBuilder.Entity("UserManagement.Models.Availability", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("avilabilityId")
                        .HasColumnType("int");

                    b.Property<int>("Avail_Status")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("day_of_week")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<TimeOnly>("time")
                        .HasColumnType("time");

                    b.HasKey("InstructorId", "avilabilityId");

                    b.HasIndex("Avail_Status");

                    b.ToTable("Availabilities", "users");

                    b.HasData(
                        new
                        {
                            InstructorId = 101,
                            avilabilityId = 1,
                            Avail_Status = 1,
                            day_of_week = 1,
                            time = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            InstructorId = 101,
                            avilabilityId = 2,
                            Avail_Status = 3,
                            day_of_week = 3,
                            time = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            InstructorId = 102,
                            avilabilityId = 3,
                            Avail_Status = 2,
                            day_of_week = 2,
                            time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            InstructorId = 102,
                            avilabilityId = 4,
                            Avail_Status = 4,
                            day_of_week = 4,
                            time = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            InstructorId = 103,
                            avilabilityId = 5,
                            Avail_Status = 1,
                            day_of_week = 5,
                            time = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            InstructorId = 104,
                            avilabilityId = 6,
                            Avail_Status = 3,
                            day_of_week = 6,
                            time = new TimeOnly(13, 0, 0)
                        });
                });

            modelBuilder.Entity("UserManagement.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("BatchDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("BatchEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("BatchStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BatchStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BatchTimeline")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("admin_ProfileAdminId")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("BatchName")
                        .IsUnique();

                    b.HasIndex("admin_ProfileAdminId");

                    b.ToTable("Batches", "users");
                });

            modelBuilder.Entity("UserManagement.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("Experience_Level")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<string>("GithubUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstructorCV")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Specialization")
                        .HasMaxLength(80)
                        .HasColumnType("int");

                    b.Property<int>("Teaching_Style")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("Years_of_Experience")
                        .HasColumnType("int");

                    b.HasKey("InstructorId");

                    b.HasIndex("Specialization");

                    b.ToTable("Instructors", "users");

                    b.HasData(
                        new
                        {
                            InstructorId = 101,
                            Experience_Level = 1,
                            GithubUserName = "aliceGH",
                            InstructorCV = "https://example.com/cv/alice.pdf",
                            ProfileImage = "https://example.com/images/alice.jpg",
                            Specialization = 0,
                            Teaching_Style = 0,
                            Years_of_Experience = 5
                        },
                        new
                        {
                            InstructorId = 102,
                            Experience_Level = 2,
                            GithubUserName = "bobDev",
                            InstructorCV = "https://example.com/cv/bob.pdf",
                            ProfileImage = "https://example.com/images/bob.jpg",
                            Specialization = 4,
                            Teaching_Style = 1,
                            Years_of_Experience = 8
                        },
                        new
                        {
                            InstructorId = 103,
                            Experience_Level = 0,
                            GithubUserName = "carolCode",
                            InstructorCV = "https://example.com/cv/carol.pdf",
                            ProfileImage = "https://example.com/images/carol.jpg",
                            Specialization = 5,
                            Teaching_Style = 2,
                            Years_of_Experience = 3
                        },
                        new
                        {
                            InstructorId = 104,
                            Experience_Level = 2,
                            GithubUserName = "daveTech",
                            InstructorCV = "https://example.com/cv/dave.pdf",
                            ProfileImage = "https://example.com/images/dave.jpg",
                            Specialization = 7,
                            Teaching_Style = 3,
                            Years_of_Experience = 10
                        });
                });

            modelBuilder.Entity("UserManagement.Models.InstructorSkill", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorSkillId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthsOfExperience")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InstructorId", "InstructorSkillId");

                    b.HasIndex("SkillName");

                    b.ToTable("InstructorSkills", "users");
                });

            modelBuilder.Entity("UserManagement.Models.Responsibility", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsibilityTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AdminProfileAdminId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsibilityDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId", "ResponsibilityTitle");

                    b.HasIndex("AdminProfileAdminId");

                    b.HasIndex("ResponsibilityTitle")
                        .IsUnique();

                    b.ToTable("Responsibilities", "users");
                });

            modelBuilder.Entity("UserManagement.Models.Trainee", b =>
                {
                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("EducationalBackground")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Experience_Level")
                        .HasColumnType("int");

                    b.Property<string>("GithubUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LearningObjectives")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Learning_Style")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Study_Focus")
                        .HasColumnType("int");

                    b.Property<string>("TraineeCV")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Years_of_Experience")
                        .HasColumnType("int");

                    b.HasKey("TraineeId");

                    b.HasIndex("BatchId");

                    b.ToTable("Trainees", "users");
                });

            modelBuilder.Entity("UserManagement.Models.TraineeSkill", b =>
                {
                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int>("TraineeSkillId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthsOfExperience")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TraineeId", "TraineeSkillId");

                    b.HasIndex("SkillName");

                    b.ToTable("TraineeSkills", "users");
                });

            modelBuilder.Entity("BatchInstructor", b =>
                {
                    b.HasOne("UserManagement.Models.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchesBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.Models.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorsInstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InstructorTrainee", b =>
                {
                    b.HasOne("UserManagement.Models.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorsInstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserManagement.Models.Trainee", null)
                        .WithMany()
                        .HasForeignKey("TraineesTraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserManagement.Models.Availability", b =>
                {
                    b.HasOne("UserManagement.Models.Instructor", "Instructor")
                        .WithMany("Availabilities")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("UserManagement.Models.Batch", b =>
                {
                    b.HasOne("UserManagement.Models.Admin_Profile", "admin_Profile")
                        .WithMany("Batchs")
                        .HasForeignKey("admin_ProfileAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin_Profile");
                });

            modelBuilder.Entity("UserManagement.Models.InstructorSkill", b =>
                {
                    b.HasOne("UserManagement.Models.Instructor", "Instructor")
                        .WithMany("instructorSkills")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("UserManagement.Models.Responsibility", b =>
                {
                    b.HasOne("UserManagement.Models.Admin_Profile", "AdminProfile")
                        .WithMany("Responsibilitys")
                        .HasForeignKey("AdminProfileAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminProfile");
                });

            modelBuilder.Entity("UserManagement.Models.Trainee", b =>
                {
                    b.HasOne("UserManagement.Models.Batch", "Batch")
                        .WithMany("Trainees")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("UserManagement.Models.TraineeSkill", b =>
                {
                    b.HasOne("UserManagement.Models.Trainee", "Trainee")
                        .WithMany("traineeSkills")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("UserManagement.Models.Admin_Profile", b =>
                {
                    b.Navigation("Batchs");

                    b.Navigation("Responsibilitys");
                });

            modelBuilder.Entity("UserManagement.Models.Batch", b =>
                {
                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("UserManagement.Models.Instructor", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("instructorSkills");
                });

            modelBuilder.Entity("UserManagement.Models.Trainee", b =>
                {
                    b.Navigation("traineeSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
